import SwiftUI
import AppKit

struct ClipboardManager {
    static let pasteSessionType = NSPasteboard.PasteboardType("com.VoiceInk.PasteSession")
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    enum ClipboardError: Error {
        case copyFailed
        case accessDenied
    }

    static func setClipboard(_ text: String, transient: Bool = false, sessionID: String? = nil) -> Bool {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        guard pasteboard.setString(text, forType: .string) else {
            return false
        }

        if let bundleIdentifier = Bundle.main.bundleIdentifier {
            pasteboard.setString(bundleIdentifier, forType: sourceType) // Non-fatal: metadata only
        }

        if transient {
            pasteboard.setData(Data(), forType: transientType)
            pasteboard.setData(Data(), forType: autoGeneratedType)
        }

        if let sessionID, !pasteboard.setString(sessionID, forType: pasteSessionType) {
            return false
        }

        return pasteboard.string(forType: .string) == text
    }

    // The string is promised, not written: `provider` supplies it on the first read, which is how a
    // paste session learns the target app has consumed its Cmd+V. Reading it back here would
    // trigger that read, so the write is verified through the session marker instead.
    static func setPromisedClipboard(
        provider: NSPasteboardItemDataProvider,
        sessionID: String,
        on pasteboard: NSPasteboard = .general
    ) -> Bool {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setDataProvider(provider, forTypes: [.string])
        if let bundleIdentifier = Bundle.main.bundleIdentifier {
            item.setString(bundleIdentifier, forType: sourceType)
        }
        item.setData(Data(), forType: transientType)
        item.setData(Data(), forType: autoGeneratedType)
        item.setString(sessionID, forType: pasteSessionType)
        return pasteboard.writeObjects([item]) && pasteboard.string(forType: pasteSessionType) == sessionID
    }

    static func copyToClipboard(_ text: String) -> Bool {
        return setClipboard(text, transient: false)
    }

    static func getClipboardContent() -> String? {
        return NSPasteboard.general.string(forType: .string)
    }
}

struct ClipboardMessageModifier: ViewModifier {
    @Binding var message: String
    
    func body(content: Content) -> some View {
        content
            .overlay(
                Group {
                    if !message.isEmpty {
                        Text(message)
                            .font(.caption)
                            .foregroundColor(.green)
                            .padding(.horizontal, 8)
                            .padding(.vertical, 4)
                            .background(Color.green.opacity(0.1))
                            .cornerRadius(4)
                            .transition(.opacity)
                            .animation(.easeInOut, value: message)
                    }
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topTrailing)
                .padding()
            )
    }
}

extension View {
    func clipboardMessage(_ message: Binding<String>) -> some View {
        self.modifier(ClipboardMessageModifier(message: message))
    }
}
